[bind_address]
addr = "127.0.0.1:8080"

[allowed_origin]
addr = "http://localhost:3000"

[quin_client_address]
addr = "0.0.0.0:0"

[quin_reporter]
host_name = ""
port = ""
addr = "127.0.0.1:5454"


[quin_inserter]
hoat_name = ""
port = ""
addr = "127.0.0.1:5455"

[quin_server_application]    
app = "localhost"

[fusion_auth_server_address]
addr = "http://localhost:9011"

[fusion_auth_api_key]
key = "gw_awXW6h11DZ7ncwyim23-wQ76IAsM947L5p9Wb7yYOR0Erh_yQKCD4"